# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20170412_1313'),
        ('instrutor', '0004_auto_20170422_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='regra',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_solicitadas', to='usuario.Usuario'),
        ),
    ]
