# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0005_regra_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regra',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_regras', to='usuario.Usuario'),
        ),
    ]
