# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_auto_20170523_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacao',
            name='regras',
        ),
    ]
