# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20170521_1454'),
        ('aluno', '0004_auto_20170521_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.Atividade'),
            preserve_default=False,
        ),
    ]
