# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_auto_20170524_0003'),
        ('aluno', '0005_recomendacao_atividade'),
    ]

    operations = [
    ]
