# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_auto_20170524_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='regras',
            field=models.ManyToManyField(related_name='recomendacoes', to='instrutor.Regra'),
        ),
    ]
