# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_merge_20170524_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Atividade'),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='regras',
            field=models.ManyToManyField(related_name='recomendacoes', to='instrutor.Regra'),
        ),
    ]
