# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_auto_20170524_0739'),
        ('aluno', '0008_auto_20170524_0957'),
    ]

    operations = [
    ]
