# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0002_auto_20170412_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regra',
            name='maleficios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maleficios', to='aluno.Caracteristica'),
        ),
    ]
