# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20170412_1253'),
        ('instrutor', '0003_auto_20170422_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regra',
            name='beneficios',
        ),
        migrations.RemoveField(
            model_name='regra',
            name='maleficios',
        ),
        migrations.AddField(
            model_name='regra',
            name='beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficio', to='aluno.Caracteristica'),
        ),
        migrations.AddField(
            model_name='regra',
            name='maleficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maleficio', to='aluno.Caracteristica'),
        ),
        migrations.AlterField(
            model_name='regra',
            name='restricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricao', to='aluno.Caracteristica'),
        ),
    ]
