# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0006_auto_20170426_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='regra',
            name='data_solicitacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
