# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='datanascimento',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
