# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20170425_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
