# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_usuario_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='auth_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='situacao',
            field=models.IntegerField(null=True),
        ),
    ]
