# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_merge_20170620_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
