# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0019_usuario_ultima_msg_excluida'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagensExcluidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_msg_excluida', models.IntegerField(default=0)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_msg_excluida', to='usuario.Usuario')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente_msg_excluida', to='usuario.Usuario')),
            ],
        ),
    ]
