# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0020_mensagensexcluidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_msg_excluida',
        ),
    ]
