# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0007_regra_data_solicitacao'),
        ('aluno', '0004_remove_recomendacao_regras'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='regras',
            field=models.ManyToManyField(related_name='recomendacoes', to='instrutor.Regra'),
        ),
    ]
