# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_recomendacao_regras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='regras',
            field=models.ManyToManyField(null=True, related_name='recomendacoes', to='instrutor.Regra'),
        ),
    ]
