# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, to='aluno.Caracteristica'),
        ),
    ]
