# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20170412_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, null=True, to='aluno.Caracteristica'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='classificacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Classificacao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacao',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='instrutor.Profissao'),
        ),
    ]
