# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20170424_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
