# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20170426_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_identificacao',
            field=models.CharField(choices=[('CRM', 'CRM'), ('CREFITO', 'CREFITO'), ('CREF', 'CREF')], default='CRM', max_length=5),
        ),
    ]
