# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_usuario_tipo_identificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacidade',
            field=models.IntegerField(null=True),
        ),
    ]
