# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-21 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_usuario_tipo_identificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='somapessoas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
