# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_post_privacidade'),
        ('usuario', '0009_auto_20170521_1454'),
    ]

    operations = [
    ]
