# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20170618_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='usuario.Usuario'),
            preserve_default=False,
        ),
    ]
