# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_merge_20170524_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cadastro_caracteristica_completo',
            field=models.IntegerField(default=0),
        ),
    ]
