# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_usuario_cadastro_caracteristica_completo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cadastro_caracteristica_completo',
            new_name='cadastro_completo',
        ),
    ]
