# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_auto_20170524_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cadastro_completo',
            field=models.IntegerField(default=1),
        ),
    ]
