# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20170524_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='somanota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
