# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20170524_1016'),
        ('usuario', '0010_auto_20170524_0835'),
    ]

    operations = [
    ]
