# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_merge_20170524_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='seguidores',
        ),
        migrations.AddField(
            model_name='usuario',
            name='associado',
            field=models.ManyToManyField(blank=True, related_name='associados', to='usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='seguindo',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to='usuario.Usuario'),
        ),
    ]
