# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_auto_20170607_0952'),
        ('usuario', '0014_auto_20170529_2107'),
    ]

    operations = [
    ]
