# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_merge_20170620_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliador', to='usuario.Usuario')),
                ('dono_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono', to='usuario.Usuario')),
            ],
        ),
    ]
