# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_merge_20170614_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
