# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_auto_20170615_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
