# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_merge_20170621_1001'),
        ('usuario', '0021_remove_usuario_ultima_msg_excluida'),
    ]

    operations = [
    ]
