# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_remove_usuario_ultima_msg_excluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recomendadas',
            field=models.CharField(default='', max_length=500),
        ),
    ]
